- hosts: fabric
  connection: httpapi
  gather_facts: false
  collections:
    - dellemc.enterprise_sonic

  tasks: 
    - name: Delete all system related configs in device configuration
      dellemc.enterprise_sonic.sonic_system:
        config:
        state: deleted
