---
- name: Delete full config
  hosts: fabric
  connection: network_cli
  gather_facts: false
  #collections:
  #  - dellemc.enterprise_sonic
  tasks:
    - name: Erase
      cli_command:
        command: write erase
        prompt:
        - All Configs except mgmt0 and user/psw will be removed.
        answer: 
        -y
        
    - name: Reboot
      tags: reboot 
        become: true
        reboot:

    - name: Wait for system to get ready
      command: "show system status"
      register: result
      until: result.stdout.find("System is ready") >= 0
      retries: 15
      delay: 15
